server:
  port: 8200
spring:
  application:
    name: project-service
  data:
    redis:
      connect-timeout:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      EmployeeClientRetrier:
        max-attempts: 2 #2 ~7s, 3 ~11s
        wait-duration: 1s
